name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull latest code
        run: |
          cd /home/ubuntu/erp-project/github-action-devops-flaskapp
          git reset --hard HEAD
          git clean -fd
          git pull origin main

      - name: Install dependencies in existing venv
        run: |
          source /home/ubuntu/erp-project/github-action-devops-flaskapp/env/bin/activate
          pip install --upgrade pip
          pip install -r /home/ubuntu/erp-project/github-action-devops-flaskapp/requirements.txt

      - name: Restart Flask service
        run: |
          sudo systemctl restart flask-app.service
